In [49]:
import numpy as np 


l1 = [1,2,3,4]
l2 = np.random.rand(3,4).tolist()
print(l2)
print(l2[1][1])

[[0.44463590300429245, 0.011998301788479382, 0.38872802680783336, 0.30673422826655816], [0.06324233775079346, 0.7029497275567136, 0.8665771420885794, 0.7451234516295151], [0.7862617616703629, 0.6183104792250189, 0.4839315053013751, 0.19682137499638286]]
0.7029497275567136


### 一维数组-np.ndarray

In [2]:
import numpy as np
a_l = [12,23,33,46]
a_array = np.array(a_l)
print(a_array)

[12 23 33 46]


In [8]:
### 索引，切片，元素类型，
### 标准差，平均数 ，和向量

# 根据索引查询
e = a_array[0]

# 切片
b_array = a_array[2:3]
print(b_array)

# 元素类型
print('元素类型: {}'.format(a_array.dtype))

# 平均值
print('平均值：{}'.format(a_array.mean()))

# 标准差
print('标准差：{}'.format(a_array.std()))

#运算,作用于每个元素
c = a_array * 4
print(c)

[33]
元素类型: int64
平均值：28.5
标准差：12.539936203984453
[ 48  92 132 184]


### pandas一维数组-Series

In [10]:
import pandas as pd

stock = pd.Series([54.74, 190.9, 173.14, 1050.3, 181.86, 1139.49], index = ['腾讯', '阿里巴巴','苹果','谷歌','Facebook','Amazon'])
print(stock)

腾讯            54.74
阿里巴巴         190.90
苹果           173.14
谷歌          1050.30
Facebook     181.86
Amazon      1139.49
dtype: float64


In [12]:
# 所以说pd有一套命名的索引，也有一套数字索引。。。
# 1. 索引
print(stock.iloc[3])
print(stock[3])
# 2. 根据index
print(stock.loc['Facebook'])

1050.3
1050.3
181.86


In [13]:
# 3. 向量运算，索引相同才能相加
a_s = pd.Series([1,2,3,4], index=['a','b','c','d'])
b_s = pd.Series([11,22,33,44], index=['a','b','e','f'])
c_s = a_s + b_s 
print(c_s)

a    12.0
b    24.0
c     NaN
d     NaN
e     NaN
f     NaN
dtype: float64


In [16]:
# NaN数据处理

# 清除NaN
print(c_s.dropna())
# 用某个值填充NaN
print('填充NaN')
print(c_s.fillna(0))

a    12.0
b    24.0
dtype: float64
填充NaN
a    12.0
b    24.0
c     0.0
d     0.0
e     0.0
f     0.0
dtype: float64


### numpy二维数组


In [52]:
# 定义
a =np.array([ [1,2,3,4],
                    [5,6,7,8],
                    [9,10,11,12] ])
print(a)

# 索引
# TypeError: list indices must be integers or slices, not tuple, list 不能用
print(a[2,2])
print(a[2][2])

# 取最后一列
print('最后一列：{}'.format(a[:][-1]))

# NumPy数轴参数 axis按轴计算平均数 1表示行，0表示 列
# 按行轴计算平均数 
print(a.mean(axis=1))
# 按列 计算 平均数 
print(a.mean(axis=0))


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
11
11
最后一列：[ 9 10 11 12]
[ 2.5  6.5 10.5]
[5. 6. 7. 8.]


### pandas二维数组-DataFrame

In [27]:
salesDict={    '购药时间':['2018-01-01 星期五','2018-01-02 星期六','2018-01-06 星期三'],   
                   '社保卡号':['001616528','001616528','0012602828'],    
                   '商品编码':[236701,236701,236701],   
                   '商品名称':['强力VC银翘片','清热解毒口服液','感康'],    
                   '销售数量':[6,1,2],    
                   '应收金额':[82.8,28,16.8],    
                   '实收金额':[69,24.64,15] }
# 建立 导入有序字典 
from collections import OrderedDict 
#定义有序字典
salesOrderDict = OrderedDict(salesDict)
saleDataFrame =pd.DataFrame(salesOrderDict)

print(saleDataFrame)

# 根据下标查询
# 筛选某一行
print(saleDataFrame.iloc[1,2])
# 查询第一行所有列 
print(saleDataFrame.iloc[0,:])
# 查询第一列所有行 
print(saleDataFrame.iloc[:,0])

print(saleDataFrame[:1])





             购药时间        社保卡号    商品编码     商品名称  销售数量  应收金额   实收金额
0  2018-01-01 星期五   001616528  236701  强力VC银翘片     6  82.8  69.00
1  2018-01-02 星期六   001616528  236701  清热解毒口服液     1  28.0  24.64
2  2018-01-06 星期三  0012602828  236701       感康     2  16.8  15.00
236701
购药时间    2018-01-01 星期五
社保卡号         001616528
商品编码            236701
商品名称           强力VC银翘片
销售数量                 6
应收金额              82.8
实收金额                69
Name: 0, dtype: object
0    2018-01-01 星期五
1    2018-01-02 星期六
2    2018-01-06 星期三
Name: 购药时间, dtype: object
             购药时间       社保卡号    商品编码     商品名称  销售数量  应收金额  实收金额
0  2018-01-01 星期五  001616528  236701  强力VC银翘片     6  82.8  69.0


In [44]:
# 查询第0行的 商品编码的列 
print(saleDataFrame.loc[0,'商品编码'])
print('='*25)

# 查询第0行的所有列 ,Series  
print(saleDataFrame.loc[0,:])
print('='*25)

#  查询销售数量列的所有行 
print(saleDataFrame.loc[:,'销售数量'] )
print('='*25)

#上述 简便方法 
print(saleDataFrame['销售数量'])
print('='*25)

#查询某几列  
saleList =['商品名称','销售数量']
print(saleDataFrame[saleList])
print('='*25)

#通过切片功能指定范围的列  
print(saleDataFrame.loc[: ,'商品名称':'销售数量'])
print('='*25)

#条件查询 销售数量大于的1 的查询  
print(saleDataFrame.loc[:,'销售数量']>1)
print('='*25)

#查询数据框的 多少行 多少列  
print(saleDataFrame.shape)

print('='*25)
print(saleDataFrame.columns)

print(saleDataFrame.index)
print('='*25)
print(saleDataFrame.values)
print(type(saleDataFrame.values))

236701
购药时间    2018-01-01 星期五
社保卡号         001616528
商品编码            236701
商品名称           强力VC银翘片
销售数量                 6
应收金额              82.8
实收金额                69
Name: 0, dtype: object
0    6
1    1
2    2
Name: 销售数量, dtype: int64
0    6
1    1
2    2
Name: 销售数量, dtype: int64
      商品名称  销售数量
0  强力VC银翘片     6
1  清热解毒口服液     1
2       感康     2
      商品名称  销售数量
0  强力VC银翘片     6
1  清热解毒口服液     1
2       感康     2
0     True
1    False
2     True
Name: 销售数量, dtype: bool
(3, 7)
Index(['购药时间', '社保卡号', '商品编码', '商品名称', '销售数量', '应收金额', '实收金额'], dtype='object')
RangeIndex(start=0, stop=3, step=1)
[['2018-01-01 星期五' '001616528' 236701 '强力VC银翘片' 6 82.8 69.0]
 ['2018-01-02 星期六' '001616528' 236701 '清热解毒口服液' 1 28.0 24.64]
 ['2018-01-06 星期三' '0012602828' 236701 '感康' 2 16.8 15.0]]
<class 'numpy.ndarray'>


In [2]:
import pandas as pd
### pandas两个列值不等的筛选，主要是为了筛选bad case，也就是把true != pred的case挑选出来, 并进行分析

l = [[0,0,0,1],[1,1,0,1],[1,1,0,0],[2,2,0,0]]
columns = ['f1','f2','true','pred']
l_df = pd.DataFrame(l,columns=columns)
print(l_df)
b = l_df['true'] == l_df['pred']
b_l = list(b)
print(b_l)
index_l = [i for i in range(len(b_l)) if b_l[i] == False]
print(index_l)
print(l_df.iloc[index_l])

print(l_df[[False, False, True, True]])
print(l_df[ l_df['true'] == l_df['pred'] ])

   f1  f2  true  pred
0   0   0     0     1
1   1   1     0     1
2   1   1     0     0
3   2   2     0     0
[False, False, True, True]
[0, 1]
   f1  f2  true  pred
0   0   0     0     1
1   1   1     0     1
   f1  f2  true  pred
2   1   1     0     0
3   2   2     0     0
   f1  f2  true  pred
2   1   1     0     0
3   2   2     0     0


### 结论

对于二维数组，python自带的list只能按行取，按照列取需要一定的操作
例如，取二维数组的最后一列
class = [example[-1] fo example in dataset]
取numpy的最后一列

取df的最后一列

|        | 索引          |   条件     |      |
|----|----------|---------|-------|
|list一维数组索引   | [1]   |         | 0.897s|
|list二维数组索引   | [1][2]    |         | 24.15s|
|np一维数组索引  | [1]     |         | 34.48s|
|np二维数组索引 | [1][2]  [1,2]    |         | 62.53s|
|np二维数组索引|.iloc[1,2] |           |

In [12]:
#拼接df的数据，数据格式是numpy
import pandas as pd 
import numpy as np 

test_df = pd.DataFrame(columns = ['data'])
test_df['data'] = [1,2,3,4]
print(test_df)

test_df2 = pd.DataFrame(columns = ['data'])
test_df2['data'] = [5,6,7,8]
print(test_df2)

a = test_df['data'].values
b = test_df2['data'].values

print(type(test_df['data'].values))
print(np.hstack((a,b)))

   data
0     1
1     2
2     3
3     4
   data
0     5
1     6
2     7
3     8
<class 'numpy.ndarray'>
[1 2 3 4 5 6 7 8]
